language: python
python:
  - "3.7-dev"
install:
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt
  - pip install -e .
# command to run tests
script:
  - flake8 easy_gscv/models.py
  - pylint easy_gscv/models.py
  - mypy easy_gscv/models.py
  - coverage run test/test_gscv.py

after_success:
  - codecov