language: python
install:
  - pip install -r dependencies/requirements.txt
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
  - flake8 easy_gscv/models.py
  - coverage run test/test_gscv.py
after_success:
  - coveralls