language: python
python:
  - "3.7-dev"
install:
  - pip install flake8
  - pip install -r dependencies/requirements.txt
  - pip install -e .
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
  - flake8 easy_gscv/models.py
  - coverage run test/test_gscv.py

after_success:
codecov